<?php
echo '<?php>';
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<title>Find BirthDay</title>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width,initial-scale=1">';
echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">';
echo '<link rel="stylesheet" type="text/css" href="./css/style.css">';
echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>';
echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>';
echo '</head>';
echo '<body style="background-image: url(./images/birthday-images-sparkingcard.png);" class="p-r">';
echo '<div class="container fullscreen-container">';
echo '<br>';
echo '<div class="row m-80" id="">';
echo '<form name="myForm" action="" onsubmit="" method="post" class="was-validated" required>';
echo '<div class="col-sm-12">';
echo '<label for="dateofbirth">Enter Date Of Birth</label>';
echo '<input type="date" name="dateofbirth" id="dateofbirth" max="5000-12-31" >';
echo '</label>';
echo '</div>';
echo '<div class="col-sm-12 submit-btn">';
echo '<button type="button" id="submit" class="common-btn"  value="submit">submit</button>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '<div class="col-sm-12" id="bdays1" hidden>';
echo '<h1>A 90-Year Human Life in <span>Months</span></h1>';
echo '<p>Each row is 36 Months = 3 Years</p>';
echo '</div>';
echo '<div  class="row" id="bdays" hidden >';
echo '</div>';
echo '</div>';
echo '<div class="content">';
echo '<div onclick="togglePopupHide();" class="close-btn" style="cursor:pointer;">';
echo '×';
echo '</div>';
echo '<h3>Notification</h3>';
echo '<div id="dvmessage">';
echo '';
echo '</div>';
echo '</div>';
echo '<script type="text/javascript" src="./js/general.js"></script>';
echo '<script src="https://code.jquery.com/jquery-2.1.4.js"></script>';
echo '<script src="https://cdn.rawgit.com/mdehoog/Semantic-UI/6e6d051d47b598ebab05857545f242caf2b4b48c/dist/semantic.min.js"></script>';
echo '<script type="text/javascript">';
echo 'function togglePopupHide(message) {';
echo '$(".fullscreen-container").fadeTo(200, 1);';
echo '$(".content").toggle();';
echo '}';
echo '</script>';
echo '</body>';
echo '</html>';
echo '';
echo '</?php>';
?>